---
- name: Accept EC2 SSH host keys
  connection: local
  become: false
  shell: |
    ssh-keygen -F {{ inventory_hostname }} ||
      ssh-keyscan -H {{ inventory_hostname }} >> ~/.ssh/known_hosts
  register: known_hosts_script
  changed_when: "'found' not in known_hosts_script.stdout"
  
- name: "copy zipped archive"
  become: true
  synchronize:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
    recursive: true

- name: Create directory for backend
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract the zipped artifact
  shell: tar xzvf artifact.tar.gz --directory backend

- name: Install dependencies
  args:
    chdir: /home/ubuntu/backend
  shell: npm install && npm run build
         

- name: "Stop applications currently running"
  become: true
  ignore_errors: true
  command: pm2 stop default

- name: "Start backend with pm2"
  become: true
  args:
    chdir: /home/ubuntu/backend
  shell: pm2 start npm -- start